version: '3'
services:
  zookeeper:
    image: debezium/zookeeper:1.3
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:1.3
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      # For local debugging of Main
      # - ADVERTISED_HOST_NAME=192.168.1.9
  order-db:
    image: debezium/postgres:12-alpine
    ports:
      - 5433:5432
    healthcheck:
      test: "pg_isready -U postgresuser -d orderdb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: orderdb
      PGPASSWORD: postgrespw
  sagas-db:
    image: debezium/postgres:12-alpine
    ports:
      - 5433:5432
    healthcheck:
      test: "pg_isready -U postgresuser -d customerdb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: sagasdb
      PGPASSWORD: postgrespw
  customer-db:
    image: debezium/postgres:12-alpine
    ports:
      - 5433:5432
    healthcheck:
      test: "pg_isready -U postgresuser -d customerdb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: customerdb
      PGPASSWORD: postgrespw
  connect:
    image: debezium/connect:1.3
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - order-db
      - customer-db
      - sagas-db
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_source_connect_configs
      OFFSET_STORAGE_TOPIC: my_source_connect_offsets
      STATUS_STORAGE_TOPIC: my_source_connect_statuses
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KAFKA_DEBUG: "true"
      DEBUG_SUSPEND_FLAG: n
#  order-service:
#    image: nest-convoy-order-service:dev
#    ports:
#      - 8080:8080
#    links:
#      - kafka
#      - order-db
#      - sagas-db
#    depends_on:
#      - sagas-db
#      - order-db
#      - connect
#  customer-service:
#    image: nest-convoy-customer-service:dev
#    links:
#      - kafka
#      - customer-db
#      - sagas-db
#    depends_on:
#      - sagas-db
#      - customer-db
#      - connect
